--- #YAML:1.0
name:                CPAN-Site
version:             0.23
abstract:            adding site local modules
license:             perl
author:              
    - Mark Overmeer
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0.82
    Test::Pod:                     1
    version:                       0.76
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
